version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run:
          name: Setup WordPress
          command: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            sudo mv wp-cli.phar /usr/local/bin/wp

      - run:
          name: Deploy Plugin
          command: |
            wp plugin install --activate traffic-jammer

