name: Deploy to WordPress.org
on:
    release:
      types: [published] 

jobs:
    release:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: ${{ env.SLUG }}