name: Deploy to WordPress.org
on:
    release:
      types: [published]            
    workflow_dispatch:


jobs:
    release:
      runs-on: ubuntu-latest
      steps:
      - name: Update packages
        run: sudo apt-get update
      - name: Install svn
        run:  sudo apt-get install subversion
      - uses: actions/checkout@v4.2.2
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@2.1.1
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: ${{ env.SLUG }}