name: lint-code
run-name: ${{github.actor}} lint code.
on: [push]
jobs:
    phpcs:
        name: WPCS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: WPCS Check
              uses: 10up/wpcs-action@stable
              with: 
                enable_warnings: false # Enable checking for warnings (-w)
                paths: '.' # Paths to check, space separated
                excludes: '' # Paths to excludes, space separated
                standard: 'WordPress' # Standard to use. Accepts WordPress|WordPress-Core|WordPress-Docs|WordPress-Extra|WordPress-VIP-Go|WordPressVIPMinimum|10up-Default.
                standard_repo: '' # Public (git) repository URL of the coding standard
                repo_branch: 'master' # Branch of Standard repository
                phpcs_bin_path: 'phpcs' # Custom PHPCS bin path
                use_local_config: 'false' # Use local config if available
                extra_args: '' # Extra arguments passing to the command

