name: lint-code
run-name: ${{github.actor}} lint code.
on: [push]
jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-dept: 0
            - name: Install PHP_CodeSniffer
              run: | 
                curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
                php phpcs.phar --version
                
